Day 15 Categorical Encoding: Turning Categories into Turnable Signals.

In [1]:
'''
Encoding means converting data from one format to another, typically for the purpose of standardization, speed, or compression. Decoding is the reverse process, converting encoded data back to its original format.
Categorical encoding is the process of converting categorical data (data that can take on a limited, fixed number of possible values) into a numerical format that can be used in machine learning algorithms.
Types of Categorical Encoding:
1. One-Hot Encoding: Converts each category value into a new binary column (0 or 1).
2. Label Encoding: Assigns each unique category value an integer label.
3. Ordinal Encoding: Similar to label encoding but maintains the order of categories.
'''

import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

data  = pd.read_excel(r"C:\Users\MUSKAAN\Documents\M.E Folder\ML&AI\Machine Learning Journey\ml-from-basics-to-beyond\Phase_2_Data_Handling\E Commerce Dataset.xlsx", sheet_name="E Comm")
data.head(5)

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5630 entries, 0 to 5629
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CustomerID                   5630 non-null   int64
 1   Churn                        5630 non-null   int64
 2   Tenure                       5366 non-null   float64
 3   PreferredLoginDevice         5630 non-null   object
 4   CityTier                     5630 non-null   int64
 5   WarehouseToHome              5379 non-null   float64
 6   PreferredPaymentMode         5630 non-null   object
 7   Gender                       5630 non-null   object
 8   HourSpendOnApp               5375 non-null   float64
 9   NumberOfDeviceRegistered     5630 non-null   int64
 10  PreferedOrderCat             5630 non-null   object
 11  SatisfactionScore            5630 non-null   int64
 12  MaritalStatus                5630 non-null   object
 13  NumberOfAddress              5630 non-null   int64
 14  Complain                     5630 non-null   int64
 15  OrderAmountHikeFromlastYear  5365 non-null   float64
 16  CouponUsed                   5374 non-null   float64
 17  OrderCount                   5372 non-null   float64
 18  DaySinceLastOrder            5323 non-null   float64
 19  CashbackAmount               5630 non-null   float64
dtypes: float64(8), int64(7), object(5)
memory usage: 879.8+ KB

In [16]:
data.isnull().sum()

# We will be using MaritalStatus,Gender columns for encoding using pandas get_dummies.
# One-Hot Encoding
en_data_1 = ["Gender","MaritalStatus"]
pd.get_dummies(data[en_data_1], drop_first=True).head(5)

   Gender_Male  MaritalStatus_Married  MaritalStatus_Single
0        False                  False                  True
1         True                  False                  True
2         True                  False                  True
3         True                  False                  True
4         True                  False                  True

In [20]:
# To use OneHotEncoder from sklearn, we need to reshape the data and fit the encoder.
# One-Hot Encoding using sklearn
ohe = OneHotEncoder(drop='first')

# Fit and transform the data means we are applying the encoding to the specified columns and converting them into a format suitable for machine learning models.
ohe_data = ohe.fit_transform(data[en_data_1])

ohe_data.toarray()[:5]  # Convert sparse matrix to array and display first 5 rows

# To convert the encoded data back to a DataFrame with appropriate column names:
ohe_df = pd.DataFrame(ohe_data.toarray(), columns=ohe.get_feature_names_out(en_data_1))
ohe_df.head(5)

   Gender_Male  MaritalStatus_Married  MaritalStatus_Single
0          0.0                    0.0                   1.0
1          1.0                    0.0                   1.0
2          1.0                    0.0                   1.0
3          1.0                    0.0                   1.0
4          1.0                    0.0                   1.0