Handling Missing Values using Scikit Learn

In [17]:
import pandas as pd
dataset  = pd.read_excel(r"C:\Users\MUSKAAN\Documents\M.E Folder\ML&AI\Machine Learning Journey\ml-from-basics-to-beyond\Phase_2_Data_Handling\E Commerce Dataset.xlsx", sheet_name="E Comm")

In [18]:
dataset.head(5)

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [19]:
dataset.isnull().sum()

CustomerID                       0
Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64

In [20]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5630 entries, 0 to 5629
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CustomerID                   5630 non-null   int64
 1   Churn                        5630 non-null   int64
 2   Tenure                       5366 non-null   float64
 3   PreferredLoginDevice         5630 non-null   object
 4   CityTier                     5630 non-null   int64
 5   WarehouseToHome              5379 non-null   float64
 6   PreferredPaymentMode         5630 non-null   object
 7   Gender                       5630 non-null   object
 8   HourSpendOnApp               5375 non-null   float64
 9   NumberOfDeviceRegistered     5630 non-null   int64
 10  PreferedOrderCat             5630 non-null   object
 11  SatisfactionScore            5630 non-null   int64
 12  MaritalStatus                5630 non-null   object
 13  NumberOfAddress              5630 non-null   int64
 14  Complain                     5630 non-null   int64
 15  OrderAmountHikeFromlastYear  5365 non-null   float64
 16  CouponUsed                   5374 non-null   float64
 17  OrderCount                   5372 non-null   float64
 18  DaySinceLastOrder            5323 non-null   float64
 19  CashbackAmount               5630 non-null   float64
dtypes: float64(8), int64(7), object(5)
memory usage: 879.8+ KB

In [21]:
dataset.select_dtypes(include=['float64']).columns

Index(['Tenure', 'WarehouseToHome', 'HourSpendOnApp',
       'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount',
       'DaySinceLastOrder', 'CashbackAmount'],
      dtype='object')

In [22]:
# To use Scikit-Learn's SimpleImputer. SimpleImputer can handle only numerical data.
'''
We will impute missing values in numerical columns using the strategy. Strategy can be 'mean', 'median', or 'most_frequent' or 'constant'.
Mean - Replace missing values using the mean along each column.
Median - Replace missing values using the median along each column.
Most_frequent - Replace missing values using the most frequent value along each column.
Constant - Replace missing values with fill_value. This strategy can be used to replace missing values with any constant value.

Start by importing SimpleImputer from sklearn.impute module.
'''
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')

'''We will fill the columns ['Tenure', 'WarehouseToHome', 'HourSpendOnApp',
       'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount',
       'DaySinceLastOrder', 'CashbackAmount'] with the mean value of the column.
using fit_transform() method of SimpleImputer. fit_transform() method fits the imputer on the data and then transforms the data.
'''
my_arr = imputer.fit_transform(dataset[['Tenure', 'WarehouseToHome', 'HourSpendOnApp',
       'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount',
       'DaySinceLastOrder', 'CashbackAmount']])

# The output of fit_transform() is a numpy array.

In [23]:
# Converting the numpy array back to a pandas DataFrame.
pd.DataFrame(my_arr,columns=dataset.select_dtypes(include=['float64']).columns)

,Tenure,WarehouseToHome,HourSpendOnApp,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,4.000000,6.0,3.000000,11.0,1.0,1.0,5.000000,159.93
1,10.189899,8.0,3.000000,15.0,0.0,1.0,0.000000,120.90
2,10.189899,30.0,2.000000,14.0,0.0,1.0,3.000000,120.28
3,0.000000,15.0,2.000000,23.0,0.0,1.0,3.000000,134.07
4,0.000000,12.0,2.931535,11.0,1.0,1.0,3.000000,129.60
...,...,...,...,...,...,...,...,...
5625,10.000000,30.0,3.000000,18.0,1.0,2.0,4.000000,150.71
5626,13.000000,13.0,3.000000,16.0,1.0,2.0,4.543491,224.91
5627,1.000000,11.0,3.000000,21.0,1.0,2.0,4.000000,186.42
5628,23.000000,9.0,4.000000,15.0,2.0,2.0,9.000000,178.90
5629,8.000000,15.0,3.000000,13.0,2.0,2.0,3.000000,169.04